### ISSUE TITLE
Alt text for Profile Pictures overflows.

### ISSUE THREAD

**Issue by ErnestoR** [ModusCreateOrg/modir#32]
If a profile picture src is unavailable. The alt text overflows.

<img width="832" alt="Modite_Directory" src="https://user-images.githubusercontent.com/1232725/56239382-72251e80-6056-11e9-8602-7fe1e4d6605f.png">

**Comment by grgur** [comment]
Just fixed that with 
```css
  white-space: nowrap;
  overflow: hidden;
```

@ErnestoR will that work?

**Comment by ErnestoR** [comment]
Yup fixed @grgur!
