### ISSUE TITLE
All search results should be visible on map

### ISSUE THREAD

**Issue by kelchm** [ModusCreateOrg/modir#33]
When searching, all modites which match the search should be made visible on the map.

As an example, when searching for "AARP", my colleagues in the southern hemisphere are not visible on the map. 

<img width="1429" alt="Screen Shot 2019-04-16 at 3 50 34 PM" src="https://user-images.githubusercontent.com/172301/56239579-6722bc00-605f-11e9-901d-5918aeb995fb.png">

**Comment by grgur** [comment]
Search works on a number of fields, but doesn't merge project information (unless specified in Slack fields). To properly solve for this the search should probably merge more data

**Comment by kelchm** [comment]
@grgur To be clear, the expected users are returned in the search results, but I can not see anyone located deep in the southern hemisphere with a desktop-sized browser window.

Here are two examples for comparison:

<img width="634" alt="Screen Shot 2019-04-17 at 9 22 27 AM" src="https://user-images.githubusercontent.com/172301/56290995-638c4500-60f2-11e9-895c-8a50afdb83a4.png">
<img width="1583" alt="Screen Shot 2019-04-17 at 9 22 45 AM" src="https://user-images.githubusercontent.com/172301/56291001-66873580-60f2-11e9-8d1b-d4c7715d7f8c.png">

**Comment by grgur** [comment]
ah ok, that's a UI issue then :) Roger that

**Comment by slemmon** [comment]
Fixed: https://github.com/ModusCreateOrg/modir/pull/37
