### ISSUE TITLE
Loading placeholder should be replaced with a message when no matching results are found

### ISSUE THREAD

**Issue by kelchm** [ModusCreateOrg/modir#34]
As an example search for "Hello World" under the Team or Project views. In either case, a placeholder is displayed which indicates to the user that results are still loading. Instead, if no rows match the search term a message should be displayed to the user to indicate that no modites or projects match the search string.

**Comment by slemmon** [comment]
![image](https://user-images.githubusercontent.com/2476017/56532449-012cad80-6513-11e9-8fca-64dc8faf4fc9.png)
@tasteofdalife You have any prescribed guidance for this view when the search field doesn't yield any results?

**Comment by rafaelbernard** [comment]
I got this one and just made a PR.

**Comment by mitchellsimoens** [comment]
DK's no results page was implemented in last deployment few weeks ago.
