### ISSUE TITLE
Opening the app on a detail view, then pressing Left arrow to go to main causes entire site reflow

### ISSUE THREAD

**Issue by jaygarcia** [ModusCreateOrg/modir#40]
Small issue, but def worth logging. 

Steps to reproduce:

Go to: https://dir.modus.app/details/UCCG3T2TF

Press `<-`.

Demo:
![Apr-25-2019 12-50-08](https://user-images.githubusercontent.com/180031/56753574-d5026e00-6758-11e9-8eb6-f1079d9825d0.gif)

**Comment by mitchellsimoens** [comment]
Looks like the refactor fixed this. We now are using react-router so this seems to be working more as you'd expect. Before, we were not using react-router really, there was only one route and showing details was being done by inspecting the URL manually iirc. We even now have some page transitions (things should animate down/up on exit/leave).
