### ISSUE TITLE
Filtering Projects

### ISSUE THREAD

**Issue by paregorics** [ModusCreateOrg/modir#42]
There's one small thing I found, when the Project tab is active, if I search for my name there are no matching results because it's searching for project names instead of modites working on projects, but it seems like it's eternally looking for something, so maybe the search bar could say "Filter Projects" instead so it's clear.

<img width="841" alt="Filter Modites" src="https://user-images.githubusercontent.com/12277087/56832249-0c444e00-6831-11e9-8239-bf7d9ce3ead4.png">

**Comment by mitchellsimoens** [comment]
This should be working in latest release done a couple weeks ago.
