### ISSUE TITLE
Dates adding a couple of weeks on profile screen

### ISSUE THREAD

**Issue by falkonprods** [ModusCreateOrg/modir#47]
![image](https://user-images.githubusercontent.com/1200120/57794698-1bfcd700-76f9-11e9-8628-4fe0b84ed3af.png)

this screenshot taking at 9:55 PST on May 15th, 2019

Other screenshots from other profiles: 

![image](https://user-images.githubusercontent.com/1200120/57794749-3b93ff80-76f9-11e9-911e-65492a0b1cbf.png)

![image](https://user-images.githubusercontent.com/1200120/57794756-4058b380-76f9-11e9-8623-a65c3a1177a5.png)

**Comment by mitchellsimoens** [comment]
Looks like this may be fixed now:

![Screen Shot 2019-07-02 at 3 15 37 PM](https://user-images.githubusercontent.com/325473/60540100-5ab41400-9cdc-11e9-83f6-20e8125017d8.png)

Drew, looks like the location data for you is in Denver so looks like it's MST not PST so your local time may be off an hour.
