### ISSUE TITLE
Fetch users in Harvest to show their project in the UI

### ISSUE THREAD

**Issue by slemmon** [ModusCreateOrg/modir#8]
Looks like for this we'll need to set up a personal API key: https://help.getharvest.com/api-v2/authentication-api/authentication/authentication/#personal-access-tokens

Here is a list of users:
https://help.getharvest.com/api-v2/users-api/users/users/#list-all-users

But, the list of users doesn't list the project a user is on.  You can list out all of the user assignments and it'll show all of the projects and each user connected to it:
https://help.getharvest.com/api-v2/projects-api/projects/user-assignments/#list-all-user-assignments

All users on a project are here:
https://help.getharvest.com/api-v2/projects-api/projects/user-assignments/#list-all-user-assignments-for-a-specific-project

The user object has a user ID and the user's email.  If the email doesn't match between Slack and Harvest we'll have to bridge those and make a relationship object we can use to marry the records.

**Comment by grgur** [comment]
We solved this issue with manual periodic pulls
